
WHENEVER SQLERROR EXIT FAILURE;
WHENEVER SQLERROR EXIT FAILURE;

ALTER SESSION FORCE PARALLEL DDL PARALLEL 8;
ALTER SESSION FORCE PARALLEL DML PARALLEL 8;
ALTER SESSION FORCE PARALLEL QUERY PARALLEL 8;

SET SERVEROUTPUT ON;
SET HEADING OFF ECHO OFF FEEDBACK ON PAGES 0 PAGESIZE 0 TERMOUT OFF VERIFY OFF LINESIZE 110;

CREATE TABLE TMP_FAMILY_GROUP AS SELECT  RETAIL_ITEM_CD,MAX(ITEM_DESC || ' ' || NVL(CAST(RETAIL_SIZE AS VARCHAR(20)),'')) AS ITEM_DESC FROM  SAVEON_IT_STG GROUP BY RETAIL_ITEM_CD;

delete from SAVEON_MB_SRC_STG where CLIENTID='clientid';
commit;

insert into saveon_mb_src_stg select * from saveon_mb_src_stg_mstr where retailitemid not in (select retailitemid from saveon_mb_src_stg_mstr);
commit;

truncate table saveon_mb_src_stg_mstr;
insert into saveon_mb_src_stg_mstr select * from saveon_mb_src_stg;
commit;

insert into SAVEON_AV_STG select * from SAVEON_AV_STG_MSTR where AP_VENDOR_ID not in (select AP_VENDOR_ID from SAVEON_AV_STG);
commit;

truncate table SAVEON_AV_STG_MSTR;
insert into SAVEON_AV_STG_MSTR select * from SAVEON_AV_STG;
commit;

insert into SAVEON_DP_SRC_STG select * from SAVEON_DP_SRC_STG_MSTR where department_id not in (select department_id from SAVEON_DP_SRC_STG);
commit;

truncate table SAVEON_DP_SRC_STG_MSTR;
insert into SAVEON_DP_SRC_STG_MSTR select * from SAVEON_DP_SRC_STG;
commit;




CREATE TABLE SAVEON_IT_STG_MDM AS
SELECT MAX(IT.ITEM_ID)ITEM_ID ,MAX(IT.RETAIL_ITEM_CD)RETAIL_ITEM_CD,
MAX(IT.ITEM_STATUS_CD)ITEM_STATUS_CD,
MAX(it.AP_VENDOR_ID)AP_VENDOR_ID,
MAX(IT.ITEM_DESC)ITEM_DESC,
MAX(LPAD( CAST(IT.DEPT_ID AS VARCHAR2(100 BYTE)), 2,'0') ) DEPT_ID,
MAX(It.DEPT_DESC)DEPT_DESC,
MAX(LPAD( CAST(IT.CLASS_ID AS VARCHAR2(100 BYTE)), 2,'0') ) CLASS_ID,
MAX(IT.CLASS_DESC)CLASS_DESC,
MAX(LPAD( CAST(IT.CAT_ID AS VARCHAR2(100 BYTE)), 2,'0') ) CAT_ID,
MAX(IT.CAT_DESC)CAT_DESC,
MAX(IT.MERCHANDISER_NUMBER)MERCHANDISER_NUMBER,
MAX(IT.MERCHANDISER_NM)MERCHANDISER_NM,
MAX(IT.RETAIL_METRIC)RETAIL_METRIC,
MAX(IT.RETAIL_PACK)RETAIL_PACK,
MAX(IT.RETAIL_SIZE)RETAIL_SIZE,
MAX(IT.MERCH_GROUP)MERCH_GROUP,
MAX(IT.FAMILY_CD)FAMILY_CD,
MAX(IT.LEAD_ITEM_RETAIL_CD)LEAD_ITEM_RETAIL_CD,
MAX(CASE WHEN NVL(IT.MERCH_GROUP,'0')='1' THEN 'CORPORATE_BRAND' ELSE 'NATIONAL_BRAND' END)BRAND_NM,
MAX(LPAD( CAST(LV.SCAN_CODE AS VARCHAR2(100 BYTE)), 14,'0') )PADDED_UPC,
MAX(LPAD( CAST(RETAIL_ITEM_CD AS VARCHAR2(100 BYTE)), 7,'0')) PADDED_RETAIL_ITEM_CD,
LV.SCAN_CODE AS UPC,
MAX(NVL(AV.AP_VENDOR_DESCRIPTION,'UNKNOWN'))AP_VENDOR_DESCRIPTION,
MAX(NVL(DT.HIGH_LEVEL_DEPARTMENTS,'UNKNOWN'))HIGH_LEVEL_DEPARTMENTS,
'UNKNOWN' AS FAMILY_CD_DESC,
MAX(NVL(MB.Brand,'UNKNOWN')) AS IRI_BRAND_DESC,
MAX(NVL(MB.Manufacturer,'UNKNOWN')) AS IRI_VENDOR_DESC,
MAX(IT.FIRST_SCAN_DATE)FIRST_SCAN_DATE,
MAX(IT.LAST_SCAN_DATE)LAST_SCAN_DATE,
MAX(IT.FILE_DATE)FILE_DATE
FROM SAVEON_IT_STG IT join SAVEON_LV_SRC_STG LV on IT.ITEM_ID=LV.ITEM_ID
LEFT JOIN SAVEON_AV_STG AV ON AV.AP_VENDOR_ID=IT.AP_VENDOR_ID
LEFT JOIN SAVEON_DP_SRC_STG DT ON DT.DEPARTMENT_ID=IT.DEPT_ID
LEFT JOIN SAVEON_MB_SRC_STG mb on mb.retailitemid=IT.RETAIL_ITEM_CD
GROUP BY LV.SCAN_CODE;


DROP TABLE SAVEON_IT_STG;
CREATE TABLE SAVEON_IT_STG AS SELECT ITEM_ID
,M.RETAIL_ITEM_CD
,ITEM_STATUS_CD
,AP_VENDOR_ID
,M.ITEM_DESC
,LPAD( CAST(DEPT_ID AS VARCHAR2(100 BYTE)), 2,'0') DEPT_ID
,DEPT_DESC
,LPAD( CAST(CLASS_ID AS VARCHAR2(100 BYTE)), 2,'0')CLASS_ID
,CLASS_DESC
,LPAD( CAST(CAT_ID AS VARCHAR2(100 BYTE)), 2,'0') CAT_ID
,CAT_DESC
,LPAD( CAST(MERCHANDISER_NUMBER AS VARCHAR2(100 BYTE)), 2,'0') MERCHANDISER_NUMBER
,MERCHANDISER_NM
,RETAIL_METRIC
,RETAIL_PACK
,RETAIL_SIZE
,MERCH_GROUP
,FAMILY_CD
,LEAD_ITEM_RETAIL_CD
,BRAND_NM
,PADDED_UPC
,PADDED_RETAIL_ITEM_CD
,UPC
,AP_VENDOR_DESCRIPTION
,HIGH_LEVEL_DEPARTMENTS
,NVL(CASE WHEN FAMILY_CD LIKE 'I%' THEN M.ITEM_DESC ELSE F.ITEM_DESC END,FAMILY_CD_DESC)FAMILY_CD_DESC
,IRI_BRAND_DESC
,IRI_VENDOR_DESC
,FIRST_SCAN_DATE
,LAST_SCAN_DATE
,FILE_DATE
FROM SAVEON_IT_STG_MDM M
LEFT JOIN TMP_FAMILY_GROUP F on F.RETAIL_ITEM_CD=M.LEAD_ITEM_RETAIL_CD;
COMMIT;


DROP TABLE SAVEON_IT_STG_MDM;
COMMIT;

DROP TABLE TMP_FAMILY_GROUP;
COMMIT;
